spring:
  application:
    name: car-parts-shop
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/car_parts_shop
    password: root
    username: postgres


